import type { FastifyReply } from 'fastify';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';

declare module 'fastify' {
	interface FastifyInstance {
		db: NodePgDatabase<any>;
		authenticate: (
			request: FastifyRequest,
			reply: FastifyReply
		) => Promise<void>;
		signAccessToken: (payload: object) => Promise<string>;
		signRefreshToken: (payload: object) => Promise<string>;
		verifyRefreshToken: (token: string) => Promise<unknown>;
	}

	interface FastifyRequest {
		user: {
			sub?: string;
			email?: string;
			iat?: number;
			exp?: number;
			[key: string]: unknown;
		};
		// userId is automatically extracted from user.sub by auth middleware
		userId?: string;
		// requestId is automatically generated by request ID middleware
		requestId?: string;
	}
}
